import mongoose from "mongoose";

import { connectDatabase } from "../config/database.js";
import Product from "../models/Product.js";

const hoodies = [
  {
    title: "Northline Oversized Hoodie",
    brand: "Northline",
    category: "hoodie",
    description: "Heavyweight cotton hoodie in an oversized cut for everyday layers.",
    pricePaise: 249900,
    currency: "INR",
    rating: 4.8,
    reviewCount: 120,
    availability: "in_stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "stone"],
    stock: { S: 6, M: 8, L: 7, XL: 5 },
    material: "cotton",
    tags: ["oversized", "streetwear", "cotton"],
    slug: "northline-oversized-hoodie",
    url: "https://shop.agentpay.local/products/northline-oversized-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "oversized", fabric: "cotton fleece", sleeve: "long sleeve" },
    active: true,
  },
  {
    title: "Harbor Zip Hoodie",
    brand: "Harbor & Co",
    category: "hoodie",
    description: "A warm zip hoodie with a clean fit and dependable stretch.",
    pricePaise: 329900,
    currency: "INR",
    rating: 4.7,
    reviewCount: 82,
    availability: "limited",
    sizes: ["M", "L", "XL"],
    colors: ["olive", "sand"],
    stock: { M: 3, L: 2, XL: 1 },
    material: "polyester blend",
    tags: ["zip hoodie", "layering", "premium"],
    slug: "harbor-zip-hoodie",
    url: "https://shop.agentpay.local/products/harbor-zip-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "regular", fabric: "polyester blend", closure: "zip" },
    active: true,
  },
  {
    title: "Summit Fleece Hoodie",
    brand: "Summit Studio",
    category: "hoodie",
    description: "Midweight fleece hoodie designed for weekend hikes and cold commutes.",
    pricePaise: 289900,
    currency: "INR",
    rating: 4.6,
    reviewCount: 96,
    availability: "in_stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["forest", "charcoal"],
    stock: { S: 4, M: 6, L: 5, XL: 3 },
    material: "fleece",
    tags: ["fleece", "outdoor", "winter"],
    slug: "summit-fleece-hoodie",
    url: "https://shop.agentpay.local/products/summit-fleece-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "regular", fabric: "fleece", activity: "outdoor" },
    active: true,
  },
  {
    title: "Drift Crew Hoodie",
    brand: "Drift Goods",
    category: "hoodie",
    description: "A soft crew-neck hoodie built for everyday comfort and travel.",
    pricePaise: 219900,
    currency: "INR",
    rating: 4.5,
    reviewCount: 88,
    availability: "in_stock",
    sizes: ["XS", "S", "M", "L"],
    colors: ["sand", "cream"],
    stock: { XS: 2, S: 5, M: 6, L: 4 },
    material: "cotton",
    tags: ["everyday", "crew", "comfort"],
    slug: "drift-crew-hoodie",
    url: "https://shop.agentpay.local/products/drift-crew-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "relaxed", fabric: "cotton jersey", neckline: "crew" },
    active: true,
  },
  {
    title: "Aster Pullover Hoodie",
    brand: "Aster Atelier",
    category: "hoodie",
    description: "Minimalistic pullover hoodie with premium brushed interior.",
    pricePaise: 279900,
    currency: "INR",
    rating: 4.9,
    reviewCount: 142,
    availability: "in_stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["midnight", "ivory"],
    stock: { S: 4, M: 7, L: 5, XL: 3 },
    material: "brushed fleece",
    tags: ["minimal", "premium", "pullover"],
    slug: "aster-pullover-hoodie",
    url: "https://shop.agentpay.local/products/aster-pullover-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "slim", fabric: "brushed fleece", neckline: "hooded" },
    active: true,
  },
  {
    title: "Basalt Heavyweight Hoodie",
    brand: "Basalt Label",
    category: "hoodie",
    description: "Sturdy heavyweight hoodie with subtle texture and roomy sleeves.",
    pricePaise: 349900,
    currency: "INR",
    rating: 4.8,
    reviewCount: 102,
    availability: "limited",
    sizes: ["M", "L", "XL"],
    colors: ["charcoal", "ash"],
    stock: { M: 2, L: 1, XL: 2 },
    material: "heavy cotton",
    tags: ["heavyweight", "core", "winter"],
    slug: "basalt-heavyweight-hoodie",
    url: "https://shop.agentpay.local/products/basalt-heavyweight-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "oversized", fabric: "heavy cotton", weight: "12 oz" },
    active: true,
  },
  {
    title: "Morrow Performance Hoodie",
    brand: "Morrow Labs",
    category: "hoodie",
    description: "Performance hoodie with quick-dry feel for active days.",
    pricePaise: 299900,
    currency: "INR",
    rating: 4.6,
    reviewCount: 90,
    availability: "in_stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["graphite", "plum"],
    stock: { S: 5, M: 7, L: 6, XL: 4 },
    material: "performance knit",
    tags: ["performance", "active", "lightweight"],
    slug: "morrow-performance-hoodie",
    url: "https://shop.agentpay.local/products/morrow-performance-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988c2477d?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "athletic", fabric: "performance knit", activity: "training" },
    active: true,
  },
  {
    title: "Hollowstone Stadium Hoodie",
    brand: "Hollowstone",
    category: "hoodie",
    description: "Crisp, all-day stadium hoodie with softly brushed lining.",
    pricePaise: 269900,
    currency: "INR",
    rating: 4.5,
    reviewCount: 68,
    availability: "in_stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["navy", "ecru"],
    stock: { S: 3, M: 5, L: 4, XL: 3 },
    material: "cotton blend",
    tags: ["stadium", "daily wear", "soft lining"],
    slug: "hollowstone-stadium-hoodie",
    url: "https://shop.agentpay.local/products/hollowstone-stadium-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "standard", fabric: "cotton blend", occasion: "daily" },
    active: true,
  },
  {
    title: "Cinder Utility Hoodie",
    brand: "Cinder Works",
    category: "hoodie",
    description: "Utility hoodie with sleek pockets and reinforced seams.",
    pricePaise: 319900,
    currency: "INR",
    rating: 4.7,
    reviewCount: 110,
    availability: "in_stock",
    sizes: ["M", "L", "XL"],
    colors: ["steel", "black"],
    stock: { M: 4, L: 6, XL: 4 },
    material: "cotton twill",
    tags: ["utility", "pockets", "workwear"],
    slug: "cinder-utility-hoodie",
    url: "https://shop.agentpay.local/products/cinder-utility-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "relaxed", fabric: "cotton twill", pocket: "kangaroo" },
    active: true,
  },
  {
    title: "Ridge Thermal Hoodie",
    brand: "Ridge North",
    category: "hoodie",
    description: "Thermal hooded layer for crisp evenings and colder commutes.",
    pricePaise: 339900,
    currency: "INR",
    rating: 4.8,
    reviewCount: 118,
    availability: "limited",
    sizes: ["M", "L", "XL"],
    colors: ["graphite", "cinder"],
    stock: { M: 2, L: 3, XL: 2 },
    material: "thermal knit",
    tags: ["thermal", "winter", "commute"],
    slug: "ridge-thermal-hoodie",
    url: "https://shop.agentpay.local/products/ridge-thermal-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "regular", fabric: "thermal knit", warmth: "high" },
    active: true,
  },
  {
    title: "Ember Knit Hoodie",
    brand: "Ember Forge",
    category: "hoodie",
    description: "Cozy knit hoodie with a soft hand-feel and warm drape.",
    pricePaise: 259900,
    currency: "INR",
    rating: 4.4,
    reviewCount: 57,
    availability: "in_stock",
    sizes: ["S", "M", "L"],
    colors: ["moss", "camel"],
    stock: { S: 5, M: 7, L: 6 },
    material: "knit cotton",
    tags: ["knit", "cozy", "soft"],
    slug: "ember-knit-hoodie",
    url: "https://shop.agentpay.local/products/ember-knit-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "relaxed", fabric: "knit cotton", softness: "high" },
    active: true,
  },
  {
    title: "Juniper Rain Hoodie",
    brand: "Juniper Co",
    category: "hoodie",
    description: "Weather-ready hoodie with soft shell finish and relaxed profile.",
    pricePaise: 309900,
    currency: "INR",
    rating: 4.6,
    reviewCount: 95,
    availability: "in_stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["pine", "stone"],
    stock: { S: 5, M: 6, L: 5, XL: 4 },
    material: "soft shell blend",
    tags: ["rain", "outerwear", "weather-ready"],
    slug: "juniper-rain-hoodie",
    url: "https://shop.agentpay.local/products/juniper-rain-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "relaxed", fabric: "soft shell blend", weather: "rain-ready" },
    active: true,
  },
  {
    title: "Slate Canvas Hoodie",
    brand: "Slate Canvas",
    category: "hoodie",
    description: "Canvas-inspired hoodie structured for an elevated, clean look.",
    pricePaise: 289900,
    currency: "INR",
    rating: 4.5,
    reviewCount: 73,
    availability: "in_stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["slate", "taupe"],
    stock: { S: 4, M: 5, L: 4, XL: 3 },
    material: "canvas cotton",
    tags: ["canvas", "structured", "clean lines"],
    slug: "slate-canvas-hoodie",
    url: "https://shop.agentpay.local/products/slate-canvas-hoodie",
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
    attributes: { fit: "structured", fabric: "canvas cotton", silhouette: "clean" },
    active: true,
  },
];

export async function seedHoodieCatalog() {
  await connectDatabase();

  const rows = await Promise.all(hoodies.map(async (item) => {
    const canonicalKey = item.slug || item.title.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-");

    const saved = await Product.findOneAndUpdate(
      { canonicalKey },
      {
        ...item,
        canonicalKey,
        category: "hoodie",
        title: item.title,
        brand: item.brand,
        description: item.description,
        pricePaise: item.pricePaise,
        currency: item.currency,
        rating: item.rating,
        reviewCount: item.reviewCount,
        availability: item.availability,
        sizes: item.sizes,
        colors: item.colors,
        stock: item.stock,
        material: item.material,
        tags: item.tags,
        slug: item.slug,
        url: item.url,
        imageUrl: item.imageUrl,
        attributes: item.attributes,
        active: true,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true, runValidators: true }
    );

    return saved;
  }));

  console.log(`Seeded ${rows.length} hoodie catalog items.`);
  return rows;
}

export default seedHoodieCatalog;

if (import.meta.url === `file://${process.argv[1]}`) {
  seedHoodieCatalog()
    .then(() => mongoose.disconnect())
    .catch((error) => {
      console.error("Hoodie catalog seed failed:", error.message);
      mongoose.disconnect();
      process.exit(1);
    });
}
